default_context:
  project_name: 'Teiso Laser'
  project_slug: 'teiso-laser'
  domain_main: 'teiso-laser.com'
  domain_staging: 'stag.teiso-laser.com'
  docker_swarm_stack_name_main: 'teiso-laser-com'
  docker_swarm_stack_name_staging: 'stag-teiso-laser-com'
  secret_key: '33af8187c988b09042f486e3ce496885124c53040f0cb0acc61a7a82e81708fb'
  first_superuser: 'admin@teiso-laser.com'
  first_superuser_password: 'admin123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.teiso-laser.com", "https://stag.teiso-laser.com", "https://teiso-laser.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@teiso-laser.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@teiso-laser.com'
  pgadmin_default_user_password: 'admin123'
  traefik_constraint_tag: 'teiso-laser.com'
  traefik_constraint_tag_staging: 'stag.teiso-laser.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin123'
  sentry_dsn: ''
  docker_image_prefix: 'teiso'
  docker_image_backend: 'teiso_backend'
  docker_image_celeryworker: 'teiso_celeryworker'
  docker_image_frontend: 'teiso_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
